<?php

/**
* @file
* Provides IIT Global Footer block
*/


/* ***************************************** */
/* Hook Implementations                      */
/* ***************************************** */

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function iit_global_footer_help($path, $arg) {
  switch ($path) {
    case 'admin/help#iit_global_footer':
      return '<p>' . t('Provides an IIT Global Footer block for use in IIT sites in the IIT Global Footer Region.') . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function iit_global_footer_block_info() {
  $blocks['iit_global_footer'] = array(
    'info' => t('IIT Global Footer'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function iit_global_footer_block_view($delta = '') {

  // Generate the block output.
  $block = array();

  switch ($delta) {
    case 'iit_global_footer':
      if (user_access('access content')) {
        //$block['subject'] = t('IIT Global Footer');
        $block['content'] = iit_global_footer_build_contents();
      }
      break;
  }

  return $block;
}


/* ***************************************** */
/* API FUNCTIONS                             */
/* ***************************************** */

/**
 * Primary IIT Global Footer Build Content Function
 *
 * Returns the HTML block content for the IIT Global Footer block.
 *
 * @return
 *   A String of HTML formatted content for the block content variable.
 */
function iit_global_footer_build_contents() {
  $module_path = drupal_get_path('module', 'iit_global_footer');
  $html_output = '';

  // Generate HTML Output
  $html_output .= '<footer id="iit-gf-wrapper">';
  $html_output .= '<div id="iit-gf-container" class="container clearfix">';
  
  $html_output .= '<div id="iit-gf-branding-wrapper">';
  $html_output .= '<a id="iit-gf-branding" title="Illinois Institute of Technology" href="//web.iit.edu/"><img width="300" src="/' . $module_path . '/images/IIT-Footer-Logo.png" alt="IIT Logo"></a>';
  $html_output .= '<div id="iit-gf-contact" class="vcard">';
  $html_output .= '<div class="fn org">Illinois Institute of Technology</div>';
  $html_output .= '<div class="adr">';
  $html_output .= '<div class="street-address">3300 South Federal Street</div>';
  $html_output .= '<span class="locality">Chicago</span>, <abbr class="region" title="Illinois">IL</abbr> <span class="postal-code">60616-3793</span>';
  $html_output .= '</div><div class="tel">312.567.3000</div>';
  $html_output .= '</div><!-- end #iit-gf-contact --></div><!-- end #iit-gf-branding-wrapper -->';

  $html_output .= '<div id="iit-gf-links"><ul>';
  $html_output .= '<li><a title="IIT Social Media Directory" href="http://www.iit.edu/directory/social-media.shtml">IIT Social Media Directory</a></li>';
  $html_output .= '<li><a title="Contact IIT" href="//web.iit.edu/contact-us">Contact IIT</a></li>';
  $html_output .= '<li><a class="emergency-info-link" title="Emergency Information" href="//web.iit.edu/emergency">Emergency Information</a></li>';
  $html_output .= '</ul></div><!-- end #iit-gf-links -->';

  $html_output .= '</div><!-- end #iit-gf-container -->';
  $html_output .= '</footer><!-- end #iit-gf-wrapper -->';

  return $html_output;
}
